### get users
GET http://localhost:4000/api/users

###
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com"
}


### Get user by id
GET http://localhost:4000/api/users/2

### Update an user
PATCH http://localhost:4000/api/users/2
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com"
}
